<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\V2__CreateProductTables.sql" />
    <None Remove="Scripts\V3__CreateSkinTables.sql" />
    <None Remove="Scripts\V4__CreateCoreTables.sql" />
    <None Remove="Scripts\V5__CreateBridgeTable.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\20260520104700CreateSchemas.sql" />
    <EmbeddedResource Include="Scripts\V2__CreateProductTables.sql" />
    <EmbeddedResource Include="Scripts\V3__CreateSkinTables.sql" />
    <EmbeddedResource Include="Scripts\V4__CreateCoreTables.sql" />
    <EmbeddedResource Include="Scripts\V5__CreateBridgeTable.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-sqlserver" Version="7.2.0" />
  </ItemGroup>

</Project>
