<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Scripts\20260520104702CreateCategoryTable.sql" />
    <None Remove="Scripts\20260520104703CreateShadeTable.sql" />
    <None Remove="Scripts\20260520104704CreateUndertoneTable.sql" />
    <None Remove="Scripts\20260520104705CreateSkinProfileTable.sql" />
    <None Remove="Scripts\20260520104706CreateUserTable.sql" />
    <None Remove="Scripts\20260520104707CreateProductTable.sql" />
    <None Remove="Scripts\20260520104708CreateProductRecommendationTable.sql" />
    <None Remove="Scripts\20260618120004InsertProductData.sql" />
    <None Remove="Scripts\20260618120005InsertSkinProfileData.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Scripts\20260520104701CreatePriceTierTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104702CreateCategoryTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104703CreateShadeTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104704CreateUndertoneTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104705CreateSkinProfileTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104706CreateUserTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104707CreateProductTable.sql" />
    <EmbeddedResource Include="Scripts\20260520104708CreateProductRecommendationTable.sql" />
    <EmbeddedResource Include="Scripts\.sql" />
    <EmbeddedResource Include="Scripts\20260618120004InsertProductData.sql" />
    <EmbeddedResource Include="Scripts\20260618120005InsertSkinProfileData.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="dbup-sqlserver" Version="7.2.0" />
  </ItemGroup>

</Project>
