CREATE TABLE product.Brand (
    BrandId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(25) NOT NULL
);
GO

CREATE TABLE product.Category (
    CategoryId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(25) NOT NULL
);
GO

CREATE TABLE product.PriceTier (
    PriceTierId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(15) NOT NULL
);
GO