CREATE TABLE product.BRAND (
    BrandId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(25) NOT NULL UNIQUE
);
GO

CREATE TABLE product.CATEGORY (
    CategoryId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(25) NOT NULL UNIQUE
);
GO

CREATE TABLE product.PRICE_TIER (
    PriceTierId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(15) NOT NULL UNIQUE
);
GO