CREATE TABLE skin.Shade (
    ShadeId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(25) NOT NULL
);
GO

CREATE TABLE skin.Undertone (
    UndertoneId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Name VARCHAR(25) NOT NULL
);
GO