IF NOT EXISTS (
	SELECT * FROM sys.tables WHERE name LIKE 'SkinProfile'
)
BEGIN
	CREATE TABLE SkinProfile (
		SkinProfileId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
		ShadeId UNIQUEIDENTIFIER NOT NULL,
		UndertoneId UNIQUEIDENTIFIER NOT NULL,
		HasTint BIT,
		CONSTRAINT FK_SkinProfile_shade FOREIGN KEY (ShadeId) REFERENCES skin.Shade(ShadeId),
		CONSTRAINT FK_SkinProfile_undertone FOREIGN KEY (UndertoneId) REFERENCES skin.Undertone(UndertoneId)
	);
END
GO

IF NOT EXISTS (
	SELECT * FROM sys.tables WHERE name LIKE 'Users'
)
BEGIN
	CREATE TABLE Users (
		UserId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
		SkinProfileId UNIQUEIDENTIFIER NOT NULL,
		FirstName VARCHAR(50) NOT NULL,
		Surname VARCHAR(50) NOT NULL,
		Username VARCHAR(50) NOT NULL,
		Email VARCHAR(50) NOT NULL,
		PasswordHash VARCHAR(60) NOT NULL
		CONSTRAINT FK_User_SkinProfile FOREIGN KEY (SkinProfileId) REFERENCES SkinProfile(SkinProfileId)
	);
END
GO

IF NOT EXISTS (
	SELECT * FROM sys.tables WHERE name LIKE 'Product'
)
BEGIN
	CREATE TABLE Product (
		ProductId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
		BrandId UNIQUEIDENTIFIER NOT NULL,
		CategoryId UNIQUEIDENTIFIER NOT NULL,
		PriceTierId UNIQUEIDENTIFIER NOT NULL,
		Name VARCHAR(50) NOT NULL,
		ShadeName VARCHAR(20) NOT NULL,
		CONSTRAINT FK_Product_Brand FOREIGN KEY (BrandId) REFERENCES product.Brand(BrandId),
		CONSTRAINT FK_Product_Category FOREIGN KEY (CategoryId) REFERENCES product.Category(CategoryId),
		CONSTRAINT FK_Product_PriceTier FOREIGN KEY (PriceTierId) REFERENCES product.PriceTier(PriceTierId)
	);
END
GO