<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Complexion.Controllers\Complexion.Controllers.csproj" />
    <ProjectReference Include="..\Complexion.DTOs\Complexion.DTOs.csproj" />
    <ProjectReference Include="..\Complexion.Migrations\Complexion.Migrations.csproj" />
    <ProjectReference Include="..\Complexion.Models\Complexion.Models.csproj" />
    <ProjectReference Include="..\Complexion.Repository\Complexion.Repository.csproj" />
    <ProjectReference Include="..\Complexion.Services\Complexion.Services.csproj" />
  </ItemGroup>

</Project>