<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Complexion.Models\Complexion.Models.csproj" />
    <ProjectReference Include="..\Complexion.Repository\Complexion.Repository.csproj" />
    <ProjectReference Include="..\Complexion.Services\Complexion.Services.csproj" />
  </ItemGroup>

</Project>
